[base]
name = gift_manager
files = {[base]name}

[tox]
envlist =
    lint
    py{310,311,312}

minversion = 4

[testenv]
extras = test
commands_pre =
    - playwright install webkit
setenv =
    DJANGO_ENV = testing
    DJANGO_SETTINGS_MODULE = GiftManager.settings
commands = pytest \
    --basetemp={envtmpdir} \
    --cov={[base]name} \
    --cov-branch \
    --cov-fail-under=70 \
    --no-cov-on-fail \
    --cov-report term-missing \
    --cov-report html:reports/coverage-{envname} \
    --cov-report xml:reports/coverage-{envname}.xml \
    --html reports/pytest-{envname}.html \
    --junit-xml=reports/pytest-{envname}.xml \
    --self-contained-html \
    {posargs}

[testenv:lint]
basepython = python3.10
deps =
    pre-commit
    pylint
commands =
    pre-commit run --all-files --show-diff-on-failure
    pylint -j {env:PYLINT_NPROCS:1} {[base]files}

[testenv:format]
basepython = python3.10
skip_install = true
deps =
    codespell
    pre-commit
commands =
    codespell -i 3 -x .codespellignorelines -w {[base]files} pyproject.toml
    pre-commit run --all-files

[gh-actions]
python =
  3.10: py310, lint
  3.11: py311
  3.12: py312
