# Generated by Django 5.1.5 on 2025-01-28 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.TextField()),
                ('comment', models.TextField(null=True)),
                ('usual_date', models.DateField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.TextField()),
                ('comment', models.TextField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group_name', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], max_length=6)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_manager.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='shared_with',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_shared_with', through='gift_manager.EventPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GiftPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], max_length=6)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_manager.gift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gift')},
            },
        ),
        migrations.AddField(
            model_name='gift',
            name='shared_with',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_shared_with', through='gift_manager.GiftPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GiftTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tag_name', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('parent_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gift_manager.gifttag')),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='tags',
            field=models.ManyToManyField(related_name='gifts', to='gift_manager.gifttag'),
        ),
        migrations.CreateModel(
            name='GiftTagPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], max_length=6)),
                ('gift_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_manager.gifttag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gift_tag')},
            },
        ),
        migrations.AddField(
            model_name='gifttag',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_gift_tags', through='gift_manager.GiftTagPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.TextField()),
                ('family_name', models.TextField(null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(to='gift_manager.persongroup')),
            ],
        ),
        migrations.CreateModel(
            name='PersonGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], max_length=6)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_manager.persongroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.AddField(
            model_name='persongroup',
            name='shared_with',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_shared_with', through='gift_manager.PersonGroupPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PersonPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], max_length=6)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_manager.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'person')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='shared_with',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_shared_with', through='gift_manager.PersonPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('due_date', models.DateField(null=True)),
                ('comment', models.TextField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='gift_manager.gift')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='gift_manager.person')),
            ],
        ),
        migrations.CreateModel(
            name='RelationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], max_length=6)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_manager.relation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'relation')},
            },
        ),
        migrations.AddField(
            model_name='relation',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_relations', through='gift_manager.RelationPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift_manager.relationstatus'),
        ),
    ]
