# Generated by Django 5.1.5 on 2025-01-28 19:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="groups",
            field=models.ManyToManyField(blank=True, to="gift_manager.persongroup"),
        ),
    ]
