# Generated by Django 5.1.5 on 2025-01-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_manager', '0002_alter_person_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
