# Generated by Django 5.1.5 on 2025-01-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_manager', '0003_alter_person_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='usual_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
