# Generated by Django 5.1.5 on 2025-01-30 17:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0005_rename_tag_name_gifttag_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="absolute_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
