# Generated by Django 5.1.5 on 2025-01-30 18:03

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0006_event_absolute_date_event_recurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="relations",
                to="gift_manager.event",
            ),
        ),
    ]
