# Generated by Django 5.1.5 on 2025-01-31 09:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0007_relation_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
        ),
        migrations.AlterModelOptions(
            name="gift",
            options={"verbose_name": "Gift", "verbose_name_plural": "Gifts"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Person", "verbose_name_plural": "Persons"},
        ),
        migrations.AlterModelOptions(
            name="persongroup",
            options={"verbose_name": "Group", "verbose_name_plural": "Groups"},
        ),
        migrations.AlterModelOptions(
            name="relation",
            options={"verbose_name": "Relation", "verbose_name_plural": "Relations"},
        ),
        migrations.AlterModelOptions(
            name="relationstatus",
            options={"verbose_name": "Relation Status", "verbose_name_plural": "Relation Statuses"},
        ),
        migrations.AddField(
            model_name="relationstatus",
            name="status_en",
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="relationstatus",
            name="status_fr",
            field=models.TextField(null=True, unique=True),
        ),
    ]
