# Generated by Django 5.1.5 on 2025-02-09 08:43

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0008_alter_event_options_alter_gift_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="gift_manager.persongroup",
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="persons",
                to="gift_manager.person",
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="status",
            field=models.ForeignKey(
                default="Idea",
                on_delete=django.db.models.deletion.CASCADE,
                to="gift_manager.relationstatus",
            ),
        ),
    ]
