# Generated by Django 5.1.5 on 2025-02-28 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0010_alter_persongroup_options_alter_gifttag_shared_with_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventpermission",
            old_name="permission_type",
            new_name="permission_type_old",
        ),
        migrations.RenameField(
            model_name="giftpermission",
            old_name="permission_type",
            new_name="permission_type_old",
        ),
        migrations.RenameField(
            model_name="gifttagpermission",
            old_name="permission_type",
            new_name="permission_type_old",
        ),
        migrations.RenameField(
            model_name="persongrouppermission",
            old_name="permission_type",
            new_name="permission_type_old",
        ),
        migrations.RenameField(
            model_name="personpermission",
            old_name="permission_type",
            new_name="permission_type_old",
        ),
        migrations.RenameField(
            model_name="relationpermission",
            old_name="permission_type",
            new_name="permission_type_old",
        ),
    ]
