# Generated by Django 5.1.5 on 2025-02-28 21:40

from django.db import migrations
from django.db import models


def convert_permission_to_int(apps, cls_name, *args, **kwargs):
    ClsPermission = apps.get_model("gift_manager", cls_name)

    # Conversion
    for permission in ClsPermission.objects.all():
        if permission.permission_type == 10:
            permission.permission_type_old = "viewer"
        elif permission.permission_type == 20:
            permission.permission_type_old = "editor"
        elif permission.permission_type == 30:
            permission.permission_type_old = "owner"
        else:
            permission.permission_type_old = "none"
        permission.save()


def convert_int_to_permission(apps, cls_name, *args, **kwargs):
    ClsPermission = apps.get_model("gift_manager", cls_name)

    # Conversion
    for permission in ClsPermission.objects.all():
        if permission.permission_type_old == "viewer":
            permission.permission_type = 10
        elif permission.permission_type_old == "editor":
            permission.permission_type = 20
        elif permission.permission_type_old == "owner":
            permission.permission_type = 30
        else:
            permission.permission_type = 0
        permission.save()


def all_convert_permission_to_int(apps, *args, **kwargs):
    convert_permission_to_int(apps, "PersonPermission", *args, **kwargs)
    convert_permission_to_int(apps, "PersonGroupPermission", *args, **kwargs)
    convert_permission_to_int(apps, "GiftPermission", *args, **kwargs)
    convert_permission_to_int(apps, "EventPermission", *args, **kwargs)
    convert_permission_to_int(apps, "GiftTagPermission", *args, **kwargs)
    convert_permission_to_int(apps, "RelationPermission", *args, **kwargs)


def all_convert_int_to_permission(apps, *args, **kwargs):
    convert_int_to_permission(apps, "PersonPermission", *args, **kwargs)
    convert_int_to_permission(apps, "PersonGroupPermission", *args, **kwargs)
    convert_int_to_permission(apps, "GiftPermission", *args, **kwargs)
    convert_int_to_permission(apps, "EventPermission", *args, **kwargs)
    convert_int_to_permission(apps, "GiftTagPermission", *args, **kwargs)
    convert_int_to_permission(apps, "RelationPermission", *args, **kwargs)


class Migration(migrations.Migration):
    dependencies = [
        (
            "gift_manager",
            "0011_rename_permission_type_eventpermission_permission_type_old_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpermission",
            name="permission_type",
            field=models.IntegerField(
                choices=[(0, "none"), (10, "viewer"), (20, "editor"), (30, "owner")], default=10
            ),
        ),
        migrations.AddField(
            model_name="giftpermission",
            name="permission_type",
            field=models.IntegerField(
                choices=[(0, "none"), (10, "viewer"), (20, "editor"), (30, "owner")], default=10
            ),
        ),
        migrations.AddField(
            model_name="gifttagpermission",
            name="permission_type",
            field=models.IntegerField(
                choices=[(0, "none"), (10, "viewer"), (20, "editor"), (30, "owner")], default=10
            ),
        ),
        migrations.AddField(
            model_name="persongrouppermission",
            name="permission_type",
            field=models.IntegerField(
                choices=[(0, "none"), (10, "viewer"), (20, "editor"), (30, "owner")], default=10
            ),
        ),
        migrations.AddField(
            model_name="personpermission",
            name="permission_type",
            field=models.IntegerField(
                choices=[(0, "none"), (10, "viewer"), (20, "editor"), (30, "owner")], default=10
            ),
        ),
        migrations.AddField(
            model_name="relationpermission",
            name="permission_type",
            field=models.IntegerField(
                choices=[(0, "none"), (10, "viewer"), (20, "editor"), (30, "owner")], default=10
            ),
        ),
        migrations.RunPython(all_convert_permission_to_int, all_convert_int_to_permission),
    ]
