# Generated by Django 5.1.5 on 2025-03-02 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0012_eventpermission_permission_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpermission",
            name="permission_type_old",
        ),
        migrations.RemoveField(
            model_name="giftpermission",
            name="permission_type_old",
        ),
        migrations.RemoveField(
            model_name="gifttagpermission",
            name="permission_type_old",
        ),
        migrations.RemoveField(
            model_name="persongrouppermission",
            name="permission_type_old",
        ),
        migrations.RemoveField(
            model_name="personpermission",
            name="permission_type_old",
        ),
        migrations.RemoveField(
            model_name="relationpermission",
            name="permission_type_old",
        ),
    ]
