# Generated by Django 5.1.5 on 2025-03-10 14:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0013_remove_eventpermission_permission_type_old_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="gifts", to="gift_manager.gifttag"
            ),
        ),
    ]
