# Generated by Django 5.1.5 on 2025-03-24 10:35

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0014_alter_gift_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="gifttag",
            name="is_public",
            field=models.BooleanField(default=False, help_text="If true, this tag is public."),
        ),
    ]
