# Generated by Django 5.1.5 on 2025-03-24 17:00

from django.db import migrations
from django.db import models


def forward_func(apps, _):
    """Convert parent_tag to parent_tags."""
    GiftTag = apps.get_model("gift_manager", "GiftTag")
    # Store relations between tags
    tag_relations = [
        (tag.id, tag.parent_tag_id) for tag in GiftTag.objects.all() if tag.parent_tag_id
    ]

    # After storing all relations, add them to the database
    for child_id, parent_id in tag_relations:
        child_tag = GiftTag.objects.get(id=child_id)
        parent_tag = GiftTag.objects.get(id=parent_id)
        child_tag.parent_tags.add(parent_tag)


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0015_gifttag_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="gifttag",
            name="parent_tags",
            field=models.ManyToManyField(
                blank=True, related_name="child_tags", to="gift_manager.gifttag"
            ),
        ),
        migrations.RunPython(forward_func),
        migrations.RemoveField(
            model_name="gifttag",
            name="parent_tag",
        ),
    ]
