# Generated by Django 5.2.6 on 2025-11-21 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0016_convert_parent_tag_to_many_to_many"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="persongroup",
            options={"verbose_name": "Person group", "verbose_name_plural": "Person groups"},
        ),
    ]
