# Generated by Django 5.2.9 on 2025-12-12 13:58

import django.db.models.deletion
from django.db import migrations
from django.db import models

import gift_manager.models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0018_alter_gifttag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="persongroup",
            name="parent_groups",
            field=models.ManyToManyField(
                blank=True, related_name="child_groups", to="gift_manager.persongroup"
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="status",
            field=models.ForeignKey(
                default=gift_manager.models.RelationStatus.get_default_pk,
                on_delete=django.db.models.deletion.PROTECT,
                to="gift_manager.relationstatus",
            ),
        ),
    ]
