# Generated by Django 5.2.9 on 2025-12-12 14:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0019_add_parent_groups_to_persongroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="persongrouppermission",
            name="inherit_permissions",
            field=models.BooleanField(
                default=False,
                help_text="If true, this permission level cascades to all child groups",
            ),
        ),
    ]
