# Generated by Django 5.2.16 on 2026-09-24 19:45

import django.core.validators
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0027_event_schedule_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="reaction_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relation",
            name="reaction_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="relation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reaction_rating__isnull", True),
                    models.Q(("reaction_rating__gte", 1), ("reaction_rating__lte", 5)),
                    _connector="OR",
                ),
                name="relation_reaction_rating_range",
            ),
        ),
    ]
