# Generated by Django 5.2.17 on 2026-09-25 14:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0028_relation_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="self_deactivated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
