# Generated by Django 5.2.17 on 2026-09-30 21:27

import django.core.validators
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0030_trigram_search_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_birthday",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="event",
            name="is_global",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="person",
            name="birthday_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="birthday_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="birthday_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("birthday_day__gte", 1),
                        ("birthday_day__isnull", False),
                        ("birthday_day__lte", 31),
                        ("birthday_month__gte", 1),
                        ("birthday_month__isnull", False),
                        ("birthday_month__lte", 12),
                    ),
                    models.Q(
                        ("birthday_day__isnull", True),
                        ("birthday_month__isnull", True),
                        ("birthday_year__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="person_birthday_valid_day_and_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_birthday", True)),
                fields=("is_birthday",),
                name="event_single_birthday_event",
            ),
        ),
    ]
