# Generated by Django 5.2.17 on 2026-10-01 12:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0032_create_global_birthday_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="calendar_token",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="digest_frequency",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("weekly", "Weekly (Mondays)"),
                    ("daily", "Daily"),
                ],
                default="off",
                max_length=10,
                verbose_name="Reminder emails",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="digest_lookahead_days",
            field=models.PositiveSmallIntegerField(
                choices=[(7, "1 week"), (14, "2 weeks"), (30, "30 days")],
                default=14,
                verbose_name="Look ahead",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("fr", "French")],
                help_text="Language of the emails and of the calendar feed",
                max_length=10,
                verbose_name="Language",
            ),
        ),
    ]
