# Generated by Django 5.2.17 on 2026-10-01 12:47

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0033_profile_reminder_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_digest_sent_on",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
