# Generated by Django 5.2.17 on 2026-10-02 16:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0034_profile_last_digest_sent_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="interests",
            field=models.ManyToManyField(
                blank=True, related_name="interested_persons", to="gift_manager.gifttag"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
