# Generated by Django 5.2.17 on 2026-10-03 13:21

import django.core.validators
from django.conf import settings
from django.db import migrations
from django.db import models

import gift_manager.validators


class Migration(migrations.Migration):
    dependencies = [
        ("gift_manager", "0035_person_notes_and_interests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Estimated price",
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=2000,
                validators=[gift_manager.validators.validate_http_url],
                verbose_name="Link",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EUR", "EUR (€)"),
                    ("USD", "USD ($)"),
                    ("GBP", "GBP (£)"),
                    ("CHF", "CHF"),
                    ("CAD", "CAD ($)"),
                ],
                default="EUR",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Estimated price",
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=2000,
                validators=[gift_manager.validators.validate_http_url],
                verbose_name="Link",
            ),
        ),
        migrations.AddConstraint(
            model_name="gift",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__isnull", True), ("price__gte", 0), _connector="OR"),
                name="gift_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="relation",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__isnull", True), ("price__gte", 0), _connector="OR"),
                name="relation_price_non_negative",
            ),
        ),
    ]
