# Generated by Django 5.2.17 on 2026-10-05 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gift_manager", "0036_richer_gift_details"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RelationComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("created_at", "pk"),
            },
        ),
        migrations.AddField(
            model_name="relation",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relation",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_relations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="is_surprise",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="relation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("claimed_by__isnull", True),
                    ("claimed_at__isnull", False),
                    _connector="OR",
                ),
                name="relation_claimed_by_requires_claimed_at",
            ),
        ),
        migrations.AddField(
            model_name="relationcomment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="relation_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relationcomment",
            name="relation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="gift_manager.relation",
            ),
        ),
    ]
