"""Integration tests for quick action buttons functionality."""

import pytest
from django.contrib.auth.models import User
from django.test import Client
from django.urls import reverse

from gift_manager.tests.factories import PersonFactory, UserFactory


@pytest.mark.django_db
class TestQuickActionButtonsIntegration:
    """Integration tests for quick action buttons."""

    @pytest.fixture(autouse=True)
    def setup(self):
        """Set up test data."""
        self.user = UserFactory()
        self.client = Client()
        self.client.force_login(self.user)

    def test_css_classes_are_included(self):
        """Test that the modern-ux.css file is included and contains quick action styles."""
        person = PersonFactory()

        url = reverse("gift_manager:persons")
        response = self.client.get(url)

        assert response.status_code == 200
        content = response.content.decode()

        # Check that modern-ux.css is included
        assert 'modern-ux.css' in content

        # Check that the Grid.js utilities are loaded
        assert 'grid-utils.js' in content

    def test_tooltip_initialization_script_present(self):
        """Test that tooltip initialization script is present."""
        url = reverse("gift_manager:persons")
        response = self.client.get(url)

        assert response.status_code == 200
        content = response.content.decode()

        # Check that tooltip initialization is present
        assert 'initializeTooltips' in content
        assert 'data-bs-toggle="tooltip"' in content

    def test_action_button_data_attributes(self):
        """Test that action buttons have proper data attributes for modern UX."""
        url = reverse("gift_manager:persons")
        response = self.client.get(url)

        assert response.status_code == 200
        content = response.content.decode()

        # Check that the data attributes are configured in the JavaScript
        # These attributes are generated by the actionButtonsFormatter
        assert 'data-action=' in content  # data-action attribute in JavaScript template
        assert 'data-bs-toggle="tooltip"' in content  # Tooltip configuration

        # Check that grid-utils.js is loaded (contains the action button formatter)
        assert 'grid-utils.js' in content

    def test_quick_action_css_classes(self):
        """Test that quick action buttons have the correct CSS classes."""
        url = reverse("gift_manager:persons")
        response = self.client.get(url)

        assert response.status_code == 200
        content = response.content.decode()

        # Check that the modern-ux.css file is loaded (contains quick action styles)
        assert 'modern-ux.css' in content

        # Check that the Grid.js utilities are loaded (contains the action button formatter)
        assert 'grid-utils.js' in content

        # Check that the actionButtonsFormatter is configured in the JavaScript
        assert 'GridUtils.actionButtonsFormatter' in content

    def test_share_button_configuration(self):
        """Test that share button is properly configured."""
        url = reverse("gift_manager:persons")
        response = self.client.get(url)

        assert response.status_code == 200
        content = response.content.decode()

        # Check that the share button is configured in the actions array
        assert "'share'" in content  # Share action in the actions array

        # Check that the share URL is configured
        assert '"/en/share/"' in content  # Share URL configuration

        # Check that grid-utils.js is loaded (contains share button configuration)
        assert 'grid-utils.js' in content

    def test_hover_effects_css_present(self):
        """Test that hover effects CSS is present in the response."""
        url = reverse("gift_manager:persons")
        response = self.client.get(url)

        assert response.status_code == 200

        # The CSS should be loaded via the static file, so we just check it's referenced
        content = response.content.decode()
        assert 'modern-ux.css' in content

    def test_responsive_design_classes(self):
        """Test that responsive design classes are included."""
        url = reverse("gift_manager:persons")
        response = self.client.get(url)

        assert response.status_code == 200
        content = response.content.decode()

        # Check for responsive text classes in the JavaScript formatter
        # These classes are defined in the grid-utils.js file which should be loaded
        assert 'd-none d-lg-inline' in content  # Button text hidden on mobile

        # The btn-text class is generated by JavaScript, so we check that grid-utils.js is loaded
        # which contains the actionButtonsFormatter that generates this class
        assert 'grid-utils.js' in content  # Grid utilities containing btn-text class
